[package]
name = "dns-lookup"
version = "1.0.8"
edition = "2018"
authors = ["Josh Driver <keeperofdakeys@gmail.com>"]
description = "A simple dns resolving api, much like rust's unstable api. Also includes getaddrinfo and getnameinfo wrappers for libc variants."
documentation = "https://docs.rs/dns-lookup"
repository = "https://github.com/keeperofdakeys/dns-lookup/"
readme = "README.md"
keywords = ["dns", "resolve", "lookup", "getaddrinfo", "getnameinfo"]
license = "MIT/Apache-2.0"
include = [
    "src/**",
    "README.md",
    "LICENSE*",
    "Cargo.*"
]

[dependencies]
socket2 = { git = "https://github.com/rust-lang/socket2", branch="v0.4.x" }
cfg-if = "^1.0"

[target."cfg(windows)".dependencies.windows-sys]
version = "0.36.1"
features = ["Win32_Networking_WinSock", "Win32_Foundation"]

[target."cfg(unix)".dependencies]
libc = "^0.2"
